#!/bin/bash

python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_001/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_002/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_003/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_004/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_005/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_006/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_007/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_008/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_009/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_012/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_013/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_014/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_015/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_016/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_017/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_018/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_019/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_020/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_021/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_022/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_023/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_024/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_025/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_026/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_027/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_028/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_029/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_030/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_031/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_032/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_033/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_034/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_035/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_036/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_037/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_038/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_039/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_040/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_041/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_042/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_043/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_044/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_045/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_046/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_047/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_048/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/chevalier_filledupirate_049/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/feval_vampire_00/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/flaubert_madamebovary_01/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/flaubert_madamebovary_02/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/gautier_romanmomie_01/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/merimee_carmen_1/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/merimee_carmen_4/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/merimee_carmen_5/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/merimee_venusdille_1/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/merimee_venusdille_2/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_01/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_02/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_03/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_04/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_05/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_06/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_07/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_08/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_09/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_10/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_11/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_12/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_13/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_14/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_15/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_16/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_17/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_18/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_19/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_20/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_21/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_22/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_23/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_24/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_25/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_26/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/sue_mysteresdeparis_01_27/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv
python fromRoots2DeepVoice3.py /lium/corpus/synthese/SynPaFlex-1.1/emotional_synpaflex_corpus/data/zeltner_contes_02_18/ /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv

bash removeLogWavsFromMetadata.sh /lium/raid01_b/tgranjon/synpaflex/synpaflex.csv

mv synpaflex-metadata-10s.csv /lium/raid01_b/tgranjon/synpaflex
